ase: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  port: 3306
  pool: 5
  username: root
  password: password

development:
  database: jap_development
  <<: *base

test:
  database: jap_test
  <<: *base

production:
  database: jap_production
  <<: *base
